table fSiteAcesso
	lineageTag: bd644d7e-ceb9-440a-bc23-1f22fdb65447

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 98ed910a-1cca-44a3-b1e2-b3689ceccd22
		summarizeBy: count
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: a05efd6c-606c-445c-9546-4c814b23699a
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column DataCadastro
		dataType: dateTime
		formatString: General Date
		lineageTag: 78c50d8e-8812-48c3-b5e5-30cd032cb4d3
		summarizeBy: none
		sourceColumn: DataCadastro

		variation Variation
			isDefault
			relationship: 3ed2f102-3215-4f23-87e8-0ad44c87657c
			defaultHierarchy: LocalDateTable_03e03fbf-993f-423f-8fa9-344dd7378407.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column CampanhaId
		dataType: int64
		formatString: 0
		lineageTag: b2722532-e6d5-466a-b530-2219f5309263
		summarizeBy: none
		sourceColumn: CampanhaId

		annotation SummarizationSetBy = Automatic

	column NomeUsuario
		dataType: string
		lineageTag: 925cbd01-5ec3-4c22-a016-a72665827bd8
		summarizeBy: none
		sourceColumn: NomeUsuario

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5be143c4-b2e1-467f-aed4-8a83c2ef19d2
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Hora do Acesso'
		dataType: string
		lineageTag: e2a83710-662b-4277-b8de-14c5940cf470
		summarizeBy: none
		sourceColumn: Hora do Acesso

		annotation SummarizationSetBy = Automatic

	partition fSiteAcesso = m
		mode: import
		source = ```
				let
				    InstrucaoSQL = "
				        SELECT 
				    Id,
				    REPLACE(REPLACE(CPF, '.', ''), '-', '') AS CPF,
				    DataCadastro,
				    CAST(DataCadastro AS DATE) AS [Date], 
				    RIGHT('00' + CAST(DATEPART(HOUR, DataCadastro) AS VARCHAR), 2) AS [Hora do Acesso],
				    CampanhaId,
				    NomeUsuario
				FROM Site.Acesso
				WHERE Sucesso = 1
				  AND DataCadastro >= '2022-01-01'
				    ",
				    Fonte = Sql.Database("sdareconhece.digi.ag", "reconheceCitibankProd", [Query=InstrucaoSQL]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Date", type date}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

